### ISSUE TITLE
Failing to run the calibrate

### ISSUE THREAD

**Issue by HJL8055** [ucb-bar/onnxruntime-riscv#119]
Hello,
I am trying to run an int8-quantized model with clip node. But after I run the calibrate.py by the code below, it seems that I get a brken quantized model.
`python calibrate.py --model_path V4.onnx  --dataset_path ../../pb --output_model_path model_quantized.onnx --static=True --data_preprocess=None --mode=int8` 
When I try to execute the systolic_runner example minimaly modified on spike, I keep getting the following error: 
![_P4XK6Q@QN`LM{B$VM6I`@0](https://user-images.githubusercontent.com/66299911/224590386-150560a7-2141-4a12-8998-b9bc179f635d.png)
Here comes the netron view of the brken quantized model. It seems that I lose all of my clip nodes.
![D8W7G1EXPTE{0GO}QXR2(80](https://user-images.githubusercontent.com/66299911/224590840-8a755dd3-5d50-46e2-b8d4-045331aeea57.png)

**Comment by hngenc** [comment]
Can you share your model? I can try to replicate this error

**Comment by HJL8055** [comment]
> Can you share your model? I can try to replicate this error

Thanks a lot for your reply but I have already solved this error. The operator——Relu6 was used in my model, which was regarded as Relu+clip. However, the quantize tool couldn't handle nodes of clip correctly, causing the broken nodes eventually.

**Comment by hngenc** [comment]
Thanks for the update!
