### ISSUE TITLE
Question: Is there a reason that Gemmini with int8 configuration does not support GEMM operation?

### ISSUE THREAD

**Issue by KUEE1080** [ucb-bar/onnxruntime-riscv#73]
As the title said, I am just curious if there a specific reason that int8 gemmini does not support GEMM operation compared to fp32 configuration. If there is no specific reason, I am trying to implement this operation in int8 configuration.

**Comment by hngenc** [comment]
We do offload int8 GEMMs to Gemmini in fact. We use 8-bit inputs, and accumulate the results into 32-bit partial sums, before scaling the final results back down to 8-bits.

**Comment by KUEE1080** [comment]
However, it seems that inside systolic_execution_provider.cc code, only QLinearMatMul, QLinearConv, QLinearConvTranspose, QLinearConv_nhwc is supported. Also, we I run googlenet on spike gemm operation is operated on the CPU. Am I missing something?

<relevent code>
https://github.com/ucb-bar/onnxruntime-riscv/blob/2021-12-23/onnxruntime/core/providers/systolic/systolic_execution_provider.cc#:~:text=of%20op%20kernels-,%23ifdef%20SYSTOLIC_INT8,-class%20ONNX_OPERATOR_TYPED_KERNEL_CLASS_NAME(kSystolicExecutionProvider

<GoogleNet result>
![image](https://user-images.githubusercontent.com/20737367/160756303-0af2c7b3-d325-48aa-80c7-e3209c470a48.png)

**Comment by hngenc** [comment]
Oh, well, we only run quantized layers on Gemmini. It's possible that the Googlenet implementation keeps the final fully-connected layer in floating point, to maximize model accuracy.
